name: Run Hedera Pulse Snap Unit Tests

on: [push]

jobs:
  eslint:
    name: Run Hedera Pulse Snap Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out source code

      - uses: actions/setup-node@v2
        name: Set up Node.js
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: packages/hedera-wallet-snap/packages/snap

      - name: Install Dependencies in Subdirectory
        run: yarn install
        working-directory: ./packages/hedera-wallet-snap/packages/snap

      - name: Run Snap Unit Tests
        run: yarn test
        working-directory: ./packages/hedera-wallet-snap/packages/snap
